### ISSUE TITLE
Timing for shader implementation most like wrong

### ISSUE THREAD

**Issue by jlisee** [sniklaus/experiment-raytracer#1]
This is a really cool demonstration.  I ran the shader version of machines of vastly different GPU power but got basically identically timings which is pretty fishy.  I think is because the GPU work is being done in an async fashion and something like [`EXT_disjoint_timer_query_webgl2`](https://www.khronos.org/registry/webgl/extensions/EXT_disjoint_timer_query_webgl2/) would need to be used to measure the timing more accurately.

**Comment by sniklaus** [comment]
Huge thanks for pointing it out! I updated the code accordingly, looks like the previous measurements were off by an order of magnitude.
