### ISSUE TITLE
Firefox JavaScript performance issue was fixed

### ISSUE THREAD

**Issue by evilpie** [sniklaus/experiment-raytracer#2]
The JS performance issue was fixed in a recent Nightly build, which is going to be Firefox 59. [bug 1420172](https://bugzilla.mozilla.org/show_bug.cgi?id=1420172) / [bug 1425687](https://bugzilla.mozilla.org/show_bug.cgi?id=1425687)

**Comment by sniklaus** [comment]
Thank you for working on this! I will update the table once Firefox 59 rolls out on the release channel..

**Comment by sniklaus** [comment]
I just wanted to update the table accordingly. However, `performance.now()` is as of Firefox 59 rounding to two milliseconds and thus preventing me from performing meaningful measurements. Closing this until measurements with sub-millisecond accuracy become viable again.
